unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -sa terminal-features ',alacritty:RGB'

set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",alacritty:usstyle"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'odedlaz/tmux-onedark-theme'

run '~/.tmux/plugins/tpm/tpm'
