format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
[ ](fg:#1d2230)\
\n└>\\[$username@$hostname\\]$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Pictures" = ""
".config" = ""

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[cmd_duration]
min_time = 0
style = 'bg:#1d2230'
format = '[[  $duration](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[hostname]
style = '#8be8cb'
ssh_only = false
format = '[$hostname]($style)'

[username]
style_root = '#7bd389'
style_user = '#7bd389'
show_always = true
format = '[$user]($style)'
